In [19]:
#유전자 알고리즘

#초기 모집단 생성 -> 적합도 평가 -> 부모 개체 선택 -> 자식 개체 생성 -> 새로운 모집단 생성
import numpy

#w1*x1 + w2*x2 .... w6 * x6를 최대로 만드는 w1~w6값들 구하는 문제
#x1~x6의 값은 이미 정해져있음.

def cal_pop_fitness(inputs, pop): #모집단 각 염색체의 적합도를 구함
    fitness = numpy.sum(pop * inputs, axis = 1)
    return fitness

#n개의 부모중에서 크기 순서대로 선택
def select_mating_poll(pop, fitness, num_parents): #다음 세대를 만들 부모를 선택
    parents = numpy.empty((num_parents, pop.shape[1])) #num_parents만큼 부모를 선택
    for parent_num in range(num_parents):
        max_fitness_index = numpy.where(fitness == numpy.max(fitness)) #적합도가 제일 큰 세대 인덱스 선택
        #fitness 원소값들 중 최대 값을 가지는 원소의 인덱스 값을 리턴
        max_fitness_index = max_fitness_index[0][0]
        parents[parent_num, :] = pop[max_fitness_index, :]
        fitness[max_fitness_index] = -9999999    
    return parents

def crossover(parents, offspring_size):
    #offspring (n * m) -> n = 새로 생성할 염색체수, m = 염색체내의 값 갯수
    offspring = numpy.empty(offspring_size)
    crossover_point = numpy.uint8(numpy.random.randint(1, offspring_size[1] - 1))
    
    for k in range(offspring_size[0]):
        parent1_idx = k % parents.shape[0]
        parent2_idx = (k + 1) % parents.shape[0]
        offspring[k, 0:crossover_point] = parents[parent1_idx, 0:crossover_point]
        offspring[k, crossover_point:] = parents[parent2_idx, crossover_point:] 
        #crossover
    return offspring

def mutation(offspring_crossover): #돌연변이 함수
    m_ptr = numpy.uint8(numpy.random.randint(0, offspring_crossover.shape[1] - 1))
    for idx in range(offspring_crossover.shape[0]):
        random_value = numpy.random.uniform(-1.0, 1.0, 1)
        offspring_crossover[idx, m_ptr] = offspring_crossover[idx, m_ptr] + random_value
    return offspring_crossover

equation_inputs = [4, -1, 3.1, 4, -6, -4.5]
num_weights = 6

sol_per_pop = 8 #모집단의 염색체 갯수
num_parents_mating = 3 #부모 선택 갯수

pop_size = (sol_per_pop, num_weights)
new_population = numpy.random.uniform(low = -4.0, high = 4.0, size = pop_size) #초기 모집단 생성
print(new_population)

num_generations = 10
for generation in range(num_generations):
    fitness = cal_pop_fitness(equation_inputs, new_population)
    parents = select_mating_poll(new_population, fitness, num_parents_mating)#적합도 높은 부모 선택
    offspring_crossover = crossover(parents, offspring_size = (pop_size[0] - parents.shape[0], num_weights)) #일부 부모 copy할 공간 남겨놈
    offspring_mutation = mutation(offspring_crossover)
    
    new_population[0:parents.shape[0], :] = parents #엘리트 유지
    new_population[parents.shape[0]:, :] = offspring_mutation #새로운 유전자 추가
    
    print('세대 : ', generation, " => best 해 : ", numpy.max(numpy.sum(new_population * equation_inputs, axis = 1)))
    
fitness = cal_pop_fitness(equation_inputs, new_population)
best_watch_idx = numpy.where(fitness == numpy.max(fitness))

print('최적해 : ', new_population[best_watch_idx, :])
print('최적해의 적합도 : ', fitness[best_watch_idx])

[[ 1.28219887  1.31076032 -2.58449626  2.23432533  0.45158333  3.00099202]
 [-3.63903163 -1.89409755  2.90877939 -3.82467761  2.09515489 -0.01470188]
 [ 2.97086185 -0.92420564  2.03410611 -3.70648805  3.518761   -2.19522725]
 [ 3.94577824  3.6378311  -3.80818693  3.99751894  1.99983186  1.67384064]
 [ 0.78050632 -2.92106851  2.16873618  3.87236117  3.96886261  2.05195476]
 [ 1.29317629  3.60428746  2.04292214 -2.0203881   3.09554487 -2.52132726]
 [-1.42436427  2.80033487 -1.31839171 -2.20443894  2.3804023   0.19999554]
 [-3.55520807 -2.52225842 -3.96252336 -3.04103638 -1.18831572 -2.18187562]]
세대 :  0  => best 해 :  10.855053995558087
세대 :  1  => best 해 :  28.382156761002665
세대 :  2  => best 해 :  28.733005079295676
세대 :  3  => best 해 :  32.88760132371627
세대 :  4  => best 해 :  33.96423112654402
세대 :  5  => best 해 :  34.71285062676327
세대 :  6  => best 해 :  37.03606138422607
세대 :  7  => best 해 :  39.67339495169139
세대 :  8  => best 해 :  39.67339495169139
세대 :  9  => best 해 :  41.45921795752